# Generated by Django 3.1.7 on 2021-05-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20180423_0727'),
        ('profiles', '0011_accountstatus_user_name'),
    ]

    operations = [
    ]
